language: php
php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm
services:
  - mysql
before_install:
  - mysql -e "CREATE DATABASE IF NOT EXISTS test;" -u root
before_script:
  - composer self-update
  - composer install
  - mysql -e 'create database test;'
script:
  phpunit --configuration phpunit.xml